# server:
#   port: 9200
#   ssl:
#     key-store: file:/app/cert/certificate.pfx
#     key-store-password: ${KEYSTORE_PASSWORD}
#     key-store-type: PKCS12
#     enabled-protocols: TLSv1.3,TLSv1.2
#     ciphers: >-
#       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
#       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,
#       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,
#       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256

spring:
  application:
    name: oracle-replication-service
    version: 0.0.1
    dpt: 9200
    dntdom: GPB
    user: test_user
    ip: test_ip
    host: test_dns
    port: test_port

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/meta_base?currentSchema=oracle_metadata}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:kampus}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: TargetDBPool

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: oracle_metadata

  flyway:
    schemas: oracle_metadata
    enabled: true
    locations: classpath:db/migration
    url: ${DB_URL:jdbc:postgresql://localhost:5432/meta_base?currentSchema=oracle_metadata}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:kampus}

  tomcat:
    max-connections: 100 # Максимальное количество соединений
    accept-count: 100 # Максимальное количество потоков
    threads:
      max: 50 # Размер очереди запросов

  # vault config
  config:
    import: optional:vault://

  cloud:
    vault:
      uri: http://vault:8200
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret_v2_t
        default-context: ord/src/connections
        application-name: ""

      connection-timeout: 5000
      read-timeout: 15000

sources:
  connections:
    file-path: ${CONFIG_DIR:classpath:}/db-connections.json

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
    endpoint:
      health:
        show-details: always
    metrics:
      export:
        prometheus:
          enabled: true

logs-database:
  enabled: true
  task-create-partition: 0 0 0 * * ?
  url: ${DB_AUDIT_URL:jdbc:postgresql://localhost:5432/db_log?currentSchema=audit}
  username: ${DB_AUDIT_USER:postgres}
  password: ${DB_AUDIT_PASSWORD:pasword}
  driverClassName: org.postgresql.Driver
  table: "audit.jdata_oracle_log"

clean-database-logs:
  # cron expression, to switch off put value '-'
  task-cleaner-schedule: 0 0 1 * * ?
  # delete logs from db that older than X years
  clean-period: 3

logging:
  cef:
    path: logs/cef
    retention-days: 30
  level:
    root: INFO
    org:
      apache:
        flink: INFO
      springframework:
        jdbc: WARN
      hikari: WARN
    com.oraclereplicator.replicator: DEBUG
  file:
    name: logs/jdata.log
    max-size: 50MB
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"