spring:
  application:
    name: oracle-replication-service
    version: 0.0.1-ORACLE
    dpt: 912044
    dntdom: GPB
    user: test_user

  datasource:
    url: jdbc:postgresql://localhost:5432/meta_base?currentSchema=oracle_metadata
    username: postgres
    password: kampus
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: TargetDBPool

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: mssql_metadata

  flyway:
    schemas: mssql_metadata
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/meta_base?currentSchema=mssql_metadata
    user: postgres
    password: kampus

  tomcat:
    max-connections: 100 # Максимальное количество соединений
    accept-count: 100 # Максимальное количество потоков
    threads:
      max: 50 # Размер очереди запросов

sources:
  connections:
    file-path: ${CONFIG_DIR:classpath:db-connections.json}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
    endpoint:
      health:
        show-details: always
    metrics:
      export:
        prometheus:
          enabled: true

logs-database:
  enabled: true
  task-create-partition: 0 0 0 * * ?
  url: jdbc:postgresql://localhost:5432/log_db
  username: postgres
  password: kampus
  driverClassName: org.postgresql.Driver

clean-database-logs:
  # cron expression, to switch off put value '-'
  task-cleaner-schedule: 0 0 1 * * ?
  # delete logs from db that older than X years
  clean-period: 3


#  databases:
#    info:
#      - name: source_db_1
#        url: jdbc:oracle:thin:@//localhost:1521/free
#        username: system
#        password: oracPas.28
#        schema: source_db_1
#        priority: 1
#        active: true

logging:
  level:
    root: INFO
    org:
      apache:
        flink: INFO
      springframework:
        jdbc: WARN
      hikari: WARN
    com:
      example:
        flinkreplication: DEBUG
  file:
    name: logs/flink-replication.log
    max-size: 50MB
    max-history: 7
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"